### ISSUE TITLE
Generate temperature and precip climo geotiffs

### ISSUE THREAD

**Issue by adamallgood** [noaa-nws-cpc/jawf-geotiff-generator#9]
@aHartmanTheGisGuy requested 7-day and monthly climatology geotiffs

**Comment by adamallgood** [comment]
Touched base with @aHartmanTheGisGuy - what he needs is as long of a record as possible of 7-day, monthly, and seasonal precip accumulation and temperature geotiffs in order to compute climatological thresholds. This can be done by running the jawf-geotiff-generator over the whole data records. The problem is space. Each geotiff file is 4MB, and we'll need a minimum of 2 (up to 4) geotiffs per day. So that's ~4*4*365.25*30 = 175320MB = 175GB of storage, minus the monthly and seasonal geotiffs, which will add a bit more. So I'll need to ask @Donald-Garrett if there is an unused 200GB of storage lying around somewhere, maybe /cpc/gth.

**Comment by adamallgood** [comment]
Sent email to @Donald-Garrett

**Comment by adamallgood** [comment]
Have a partition! /cpc/gth/allgood-explosion. Will set up these jobs today, and will monitor their progress over the next few days.

**Comment by adamallgood** [comment]
Wei's archive only goes back to 2014. I sent him an email asking for location of 1981-2010 data.

**Comment by adamallgood** [comment]
Temperatures are running. Will check on them later this weekend or on Monday. Then will tackle precip.

**Comment by adamallgood** [comment]
Creating 1981-2010 temperature data in binary format.

**Comment by adamallgood** [comment]
Need to rerun for tmax and tmin over-ocean files. @mikecharles is backfilling dates to 1985.

**Comment by mikecharles** [comment]
> Need to rerun for tmax and tmin over-ocean files. @mikecharles is backfilling dates to 1985.

Done:

    /cpc/data/observations/land_air/short_range/global/merged_tmax/1deg/01d
    /cpc/data/observations/land_air/short_range/global/merged_tmin/1deg/01d

**Comment by adamallgood** [comment]
This is done, and data have been deleted from /cpc/gth/allgood-explosion.
